spring:
  application:
    name: servicio-cursos
  datasource:
    password: EC530A97BF69B38911923AEAA90DC477
    url: jdbc:mysql://localhost:3306/academia
    username: librouser
  cloud:
    config:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  instance:
    instanceId: Instancia1 #Cambiar nombre para cada instancia
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
server:
  port: 8080 # instancia 2 8081, Instancia 3 8082