server:
  port: 8085
spring:
  application:
    name: servicio-formacion
eureka:
  instance:
    instanceId: servicio-formacion #Cambiar nombre para cada instancia
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/   
